[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
[target.x86_64-pc-windows-gnullvm]
rustflags = [
  "-C", "target-feature=+crt-static",  # 静态链接CRT
  "-C", "link-args=/ALIGN:8"           # 段对齐
]
[target.aarch64-pc-windows-gnullvm]
rustflags = [
  "-C", "target-feature=+crt-static",  # 静态链接CRT
  "-C", "link-args=/ALIGN:8"           # 段对齐
]
