name: Rust-Cargo Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always
  CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
  CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_AR: aarch64-linux-gnu-ar
  CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER: aarch64-linux-musl-gcc
  CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_AR: aarch64-linux-musl-ar
  CARGO_TARGET_X86_64_PC_WINDOWS_GNULLVM_LINKER: "${{github.workspace}}/llvm-mingw/bin/x86_64-w64-mingw32-clang"
  CARGO_TARGET_X86_64_PC_WINDOWS_GNULLVM_AR: "${{github.workspace}}/llvm-mingw/bin/x86_64-w64-mingw32-ar"
  CARGO_TARGET_AARCH64_PC_WINDOWS_GNULLVM_LINKER: "${{github.workspace}}/llvm-mingw/bin/aarch64-w64-mingw32-clang"
  CARGO_TARGET_AARCH64_PC_WINDOWS_GNULLVM_AR: "${{github.workspace}}/llvm-mingw/bin/aarch64-w64-mingw32-ar"
  #RUSTFLAGS: "-C target-feature=+crt-static"
  name: "terracotta"
  MACOSX_DEPLOYMENT_TARGET: "11.1"
  RUST_BACKTRACE: "full"
  targets: >-
    x86_64-unknown-linux-musl 
    x86_64-unknown-linux-gnu 
    x86_64-pc-windows-gnullvm
    x86_64-pc-windows-gnu
    x86_64-apple-darwin 
    aarch64-unknown-linux-musl 
    aarch64-unknown-linux-gnu 
    aarch64-pc-windows-gnullvm 
    aarch64-apple-darwin

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    name: Build All
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    # 安装编译前置
    - name: Install Cross Compiler Toolchains
      run: |
        sudo apt update
        sudo apt install --yes --no-install-recommends build-essential \
          gcc-x86-64-linux-gnu g++-x86-64-linux-gnu \
          gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu \
          gcc-mingw-w64-x86-64 \
          musl-tools musl-dev mingw-w64
        wget -O llvm-mingw.tar.xz https://github.com/mstorsjo/llvm-mingw/releases/download/20250709/llvm-mingw-20250709-ucrt-ubuntu-22.04-x86_64.tar.xz
        tar -xf llvm-mingw.tar.xz -C ${{github.workspace}}
        mv -v ${{github.workspace}}/llvm-mingw-* ${{github.workspace}}/llvm-mingw
        #echo "${{github.workspace}}/llvm-mingw/bin" >> $GITHUB_PATH
        mv -v ".github/.cargo" "."
    - name: Install Cross Compliers (General)
      uses: Lesmiscore/musl-cross-compilers@master
      with:
        target: "aarch64-linux-musl"
    - name: Install Cross Compliers (MacOS)
      uses: 8Mi-Tech/setup-osx-cross@6b7954cec12f774c2ff02b2a7596ec6791a39ed5
      with:
        osx-version: "${{ env.MACOSX_DEPLOYMENT_TARGET }}"
    # 准备缓存 Cargo 内容
    - name: Generate Cargo.lock file
      run: cargo generate-lockfile
    - name: Check Action Event Type
      id: cargo-cache-check
      run: |
        case "${{ github.event_name }}" in
          "push"|"workflow_dispatch") echo "type=full" >> "$GITHUB_OUTPUT"; echo "path=target" >> "$GITHUB_OUTPUT" ;;
          "pull_request") echo "type=mini" >> "$GITHUB_OUTPUT" ;;
        esac
    - name: Cargo Cache Restore or Save
      id: cargo-cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ${{ steps.cargo-cache-check.outputs.path }}
        key: ${{ runner.os }}-cargo-${{ steps.cargo-cache-check.outputs.type }}-${{ hashFiles('**/Cargo.lock') }}
    - name: Clean Old Cargo Cache
      if:  ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && steps.cargo-cache.outputs.cache-hit != 'true' }}
      uses: yumemi-inc/clean-cache-action@v1
      with:
        ref: ${{ github.ref }}
        key: ${{ runner.os }}-cargo-full-
    # 编译流程
    - name: Install Rust Toolchains
      run: |
        rustup target add $(echo "$targets" | tr '\n' ' ')
    - name: Build All
      id: build
      run: |
        cargo build --release --target $(echo $(echo "$targets" | tr '\n' ' ') | sed 's/ / --target /g')
    # 二进制测试流程
    - name: Run Tests
      run: cargo test --verbose
    # 文件整理流程
    - name: Assemble Artifact
      run: |
        _targets=($(echo "$targets"))
        mkdir -p target/output
        for target in "${_targets[@]}"; do
          bin_name="$name"
          [[ "$target" == *"windows"* ]] && suffix=".exe" || suffix=""
          
          src_path="target/$target/release/$bin_name$suffix"
          if [ -f "$src_path" ]; then
              _filename=$(echo $target | sed -e 's/unknown//g; s/pc//g; s/gnullvm//g; s/darwin//g; s/aarch64/arm64/g; s/^\([^-]*\)-\(.*\)/\2-\1/; s/^[[:space:]]*-\+//; s/-\+[[:space:]]*$//; s/[[:space:]]//g; s/--/-/g; ' )
              mv "$src_path" "target/output/$bin_name"-"$_filename$suffix"
          else
            echo "[WARNING] File doesn't exist: $src_path"
          fi
        done
    # 上传到 Artifact 区
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: "terracotta-build"
        path: "target/output/*"
