name: Rust-Cargo Build

on:
  push:
    paths-ignore:
      - 'sites/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:
    inputs:
      version:
        description: Terracotta Version
        type: string

env:
  CARGO_TERM_COLOR: always
  name: "terracotta"
  RUST_BACKTRACE: "full"

defaults:
  run:
    shell: "bash"

jobs:
  windows-x86_64:
    runs-on: windows-latest
    name: Build for Windows x86_64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install GitHub Artifact Client
        uses: lhotari/gh-actions-artifact-client@v2
      - name: Compute Version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            echo "TERRACOTTA_VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV
          else
            echo "TERRACOTTA_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          fi
      - name: Build
        run: |
          rustup update nightly
          rustup target add --toolchain nightly x86_64-win7-windows-gnu
          cargo +nightly build -Zbuild-std --release
      - name: Upload Artifact
        run: |
          source="terracotta-${TERRACOTTA_VERSION}-windows-x86_64.exe"
          cp "target/release/terracotta.exe" "$source"
          tar acvf "$source.tar" "$source"
          cat "$source.tar" | gh-actions-artifact-client.js upload "$source"
  windows-arm64:
    runs-on: windows-latest
    name: Build for Windows arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install GitHub Artifact Client
        uses: lhotari/gh-actions-artifact-client@v2
      - name: Compute Version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            echo "TERRACOTTA_VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV
          else
            echo "TERRACOTTA_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          fi
      - name: Build
        run: |
          cargo install cargo-xwin
          rustup component add llvm-tools
          rustup target add --toolchain nightly aarch64-pc-windows-msvc
          cargo +nightly build --release
      - name: Upload Artifact
        run: |
          source="terracotta-${TERRACOTTA_VERSION}-windows-x86_64.exe"
          cp "target/release/terracotta.exe" "$source"
          tar acvf "$source.tar" "$source"
          cat "$source.tar" | gh-actions-artifact-client.js upload "$source"
  linux-x86_64:
    runs-on: ubuntu-latest
    name: Build for Linux x86_64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install GitHub Artifact Client
        uses: lhotari/gh-actions-artifact-client@v2
      - name: Compute Version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            echo "TERRACOTTA_VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV
          else
            echo "TERRACOTTA_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          fi
      - name: Build
        run: |
          rustup target add --toolchain nightly x86_64-unknown-linux-gnu
          cargo +nightly build --release
      - name: Upload Artifact
        run: |
          wget -O linux-deploy.AppImage https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linux-deploy.AppImage
          ./linux-deploy.AppImage --appdir="$(mktemp -d)" \
            --desktop-file=build/linux/terracotta.desktop \
            --icon-file=build/linux/icon.png \
            -e "target/release/terracotta" \
            --output=appimage

          source="terracotta-${TERRACOTTA_VERSION}-linux-x86_64.AppImage"
          mv "Terracotta-x86_64.AppImage" "$source"
          chmod 755 "$source"
          zip -q - "$source" | gh-actions-artifact-client.js upload "${source}"
  linux-arm64:
    runs-on: ubuntu-24.04-arm
    name: Build for Linux arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install GitHub Artifact Client
        uses: lhotari/gh-actions-artifact-client@v2
      - name: Compute Version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            echo "TERRACOTTA_VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV
          else
            echo "TERRACOTTA_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          fi
      - name: Build
        run: |
          rustup target add --toolchain nightly aarch64-unknown-linux-gnu
          cargo +nightly build --release
      - name: Upload Artifact
        run: |
          wget -O linux-deploy.AppImage https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-aarch64.AppImage
          chmod +x linux-deploy.AppImage
          ./linux-deploy.AppImage --appdir="$(mktemp -d)" \
            --desktop-file=build/linux/terracotta.desktop \
            --icon-file=build/linux/icon.png \
            -e "target/release/terracotta" \
            --output=appimage

          source="terracotta-${TERRACOTTA_VERSION}-linux-arm64.AppImage"
          mv "Terracotta-aarch64.AppImage" "$source"
          chmod 755 "$source"
          zip -q - "$source" | gh-actions-artifact-client.js upload "${source}"
  macos-x86_64:
    runs-on: macos-13
    name: Build for MacOS x86_64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install GitHub Artifact Client
        uses: lhotari/gh-actions-artifact-client@v2
      - name: Compute Version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            echo "TERRACOTTA_VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV
          else
            echo "TERRACOTTA_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          fi
      - name: Build
        run: |
          rustup target add --toolchain nightly x86_64-apple-darwin
          cargo +nightly build --release
      - name: Upload Artifact
        run: |
          chmod -R 755 build/macos/scripts
          TEMP_DIR=$(mktemp -d)
          mkdir -p "$TEMP_DIR"
          
          cp -R build/macos/terracotta.app "$TEMP_DIR"
          mkdir -p "$TEMP_DIR/terracotta.app/Contents/MacOS/"
          cp "target/release/terracotta" "$TEMP_DIR/terracotta.app/Contents/MacOS/terracotta"
          
          chmod -R 755 "$TEMP_DIR/"
          PKG_OUTPUT="terracotta-${TERRACOTTA_VERSION}-macos-x86_64.pkg"
          
          pkgbuild \
            --root "$TEMP_DIR" \
            --identifier "net.burningtnt.terracotta" \
            --version "1.0" \
            --install-location "/Applications" \
            --scripts build/macos/scripts \
            --component-plist build/macos/terracotta.plist \
            "$PKG_OUTPUT"
          zip -q - $PKG_OUTPUT | gh-actions-artifact-client.js upload "terracotta-${TERRACOTTA_VERSION}-macos-x86_64.pkg"
  macos-arm64:
    runs-on: macos-14
    name: Build for MacOS arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install GitHub Artifact Client
        uses: lhotari/gh-actions-artifact-client@v2
      - name: Compute Version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            echo "TERRACOTTA_VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV
          else
            echo "TERRACOTTA_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          fi
      - name: Build
        run: |
          rustup target add --toolchain nightly aarch64-apple-darwin
          cargo +nightly build --release
      - name: Upload Artifact
        run: |
          chmod -R 755 build/macos/scripts
          TEMP_DIR=$(mktemp -d)
          mkdir -p "$TEMP_DIR"
          
          cp -R build/macos/terracotta.app "$TEMP_DIR"
          mkdir -p "$TEMP_DIR/terracotta.app/Contents/MacOS/"
          cp "target/release/terracotta" "$TEMP_DIR/terracotta.app/Contents/MacOS/terracotta"
          
          chmod -R 755 "$TEMP_DIR/"
          PKG_OUTPUT="terracotta-${TERRACOTTA_VERSION}-macos-arm64.pkg"
          
          pkgbuild \
            --root "$TEMP_DIR" \
            --identifier "net.burningtnt.terracotta" \
            --version "1.0" \
            --install-location "/Applications" \
            --scripts build/macos/scripts \
            --component-plist build/macos/terracotta.plist \
            "$PKG_OUTPUT"
          zip -q - $PKG_OUTPUT | gh-actions-artifact-client.js upload "terracotta-${TERRACOTTA_VERSION}-macos-arm64.pkg"
