name: Deploy Sites
on:
  push:
    paths:
      - 'sites/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy MkDocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: sites/mkdocs.yml
          WORKING_DIR: sites
          REQUIREMENTS: sites/requirements.txt
