name: Deploy Sites
on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yaml'
  workflow_dispatch:

permissions:
  contents: write
jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Deploy MkDocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          WORKING_DIR: docs
          REQUIREMENTS: requirements.txt
