name: Publish Releases to Mirrors

on:
  workflow_dispatch:
  release:
    types: [ published ]

env:
  GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
  GITEE_OWNER: ${{ vars.GITEE_OWNER }}
  GITEE_REPO: ${{ vars.GITEE_REPO }}
  GITEE_TARGET_COMMITISH: ${{ vars.GITEE_TARGET_COMMITISH }}

  CNB_TOKEN: ${{ secrets.CNB_TOKEN }}
  CNB_OWNER: ${{ vars.CNB_OWNER }}
  CNB_REPO: ${{ vars.CNB_REPO }}
  CNB_TARGET_COMMITISH: ${{ vars.CNB_TARGET_COMMITISH }}

jobs:
  publish-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install NPM Dependencies
        run: npm install --no-save got form-data
      - name: Publish Releases to Mirrors
        uses: actions/github-script@v8
        with:
          script: |
            const publish = require('./build/publish/publish.ts');
            await publish.main({ context, octokit, require });
