# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
# 
# For more information, please refer to <https://unlicense.org>

name: Publish Releases to Mirrors

on:
  workflow_dispatch:
  release:
    types: [ published ]

env:
  GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
  GITEE_OWNER: ${{ vars.GITEE_OWNER }}
  GITEE_REPO: ${{ vars.GITEE_REPO }}
  GITEE_TARGET_COMMITISH: ${{ vars.GITEE_TARGET_COMMITISH }}

  CNB_TOKEN: ${{ secrets.CNB_TOKEN }}
  CNB_OWNER: ${{ vars.CNB_OWNER }}
  CNB_REPO: ${{ vars.CNB_REPO }}
  CNB_TARGET_COMMITISH: ${{ vars.CNB_TARGET_COMMITISH }}

jobs:
  publish-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install NPM Dependencies
        run: npm install --no-save got form-data chunk-data
      - name: Publish Releases to Mirrors
        uses: actions/github-script@v8
        with:
          script: |
            const publish = require('./build/publish/publish.ts');
            await publish.main({ context, octokit, require });
