name: PR Closed Clean
on:
  pull_request:
    types:
      - closed

jobs:
  clean:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: yumemi-inc/clean-cache-action@v1
        with:
          ref: '${{ github.ref }}'
